project:
  type: website

website:
  title: "Trevor Nederlof"
  search: false
  navbar:
    background: primary
    right:
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: "https://github.com/tnederlof/"
        icon: github
      - href: "https://www.linkedin.com/in/trevor-nederlof/"
        icon: linkedin
      - href: "https://twitter.com/tnederlof"
        icon: twitter

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



