project:
  type: website

website:
  title: "Trevor Nederlof"
  search: false
  body-footer: |
      <!-- 100% privacy-first analytics -->
      <script async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
  navbar:
    background: primary
    right:
      - href: about.qmd
        text: About
      - href: thoughts.qmd
        text: Thoughts
      - href: "https://github.com/tnederlof/"
        icon: github
      - href: "https://www.linkedin.com/in/trevor-nederlof/"
        icon: linkedin
      - href: "https://x.com/tnederlof"
        icon: twitter

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    email-obfuscation: javascript



