---
title: ""
draft: false
---

# Present

Currently, I am a Senior Solutions Engineer at [Sourcegraph](https://sourcegraph.com/) (makers of [Amp](https://ampcode.com/)), where I empower developers in enterprise organizations to reinvent their workflows in the age of agentic tools. In addition to my work with customers, I genuinely enjoy using [Amp](https://ampcode.com/) every day to build and learn.

Off the computer, I live in the Hudson Valley, New York, and spend as much time outdoors as possible. You can find me gardening, trail running/backpacking in the Catskills, or cooking up something new. I am also a fire commissioner and volunteer firefighter in Livingston, NY, where I proudly serve my community.

# Past

* Principal Solutions Architect at Posit, formerly RStudio (learned a lot about AI assistant, agentic tools, data science workflows and enterprise architectures, especially Kubernetes)
* Senior Solutions Engineer at CARTO (learned a lot about cloud infrastructure, data warehouses, geospatial analysis, and enterprise data science)
* Portfolio Solutions Developer at Neuberger Berman (learned a lot about infrastructure at a larger company with IT constraints and solution selling to large asset owners)
* Quantitative Portfolio Developer at Risk Premium Investments (learned a lot about programming, databases, infrastructure, and productionization as I was responsible for setting it all up)
* Associate at Nomura on the interest rate derivatives sales desk (learned a lot about the inner workings of the mortgage market and sales in general)
* Bachelor's degree from Drexel University in Business Administration with concentrations in Finance and Economics (when I thought global markets trading was interesting)